<?php require_once ("top.phtml"); ?>

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <?php require_once ("menu.phtml");?>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <?php require_once ("header.phtml");?>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-4 text-gray-800">Форма добавления товаров в меню</h1>

          <form>
            <div class="row">
              <div class="col-lg-6">

                <div class="form-group"><label for="product_name">Название товара</label><input type="text" class="form-control form-control-solid" id="product_name" name="product_name" rows="1"></input></div>

                <div class="form-group"><label for="comment">Описание товара</label><textarea class="form-control form-control-solid" id="comment" name="comment" rows="3"></textarea></div>
                
                <div class="form-group"><label for="ingredient">Ингредиенты</label><input type="text" class="form-control form-control-solid" id="ingredient" name="ingredient" rows="1"></input></div>

                <div class="form-group"><label for="kkal">Ккал</label><input type="text" class="form-control form-control-solid" id="kkal" name="kkal" rows="1"></input></div>
                
                <div class="form-group"><label for="protein">Белки</label><input type="text" class="form-control form-control-solid" id="protein" name="protein" rows="1"></input></div>

                <div class="form-group"><label for="fat">Жиры</label><input type="text" class="form-control form-control-solid" id="fat" name="fat" rows="1"></input></div>

                <div class="form-group"><label for="carbo">Углеводы</label><input type="text" class="form-control form-control-solid" id="carbo" name="carbo" rows="1"></input></div>
                
              </div>

              <div class="col-lg-6">
                <div class="form-group"><label for="weight">Вес</label><input type="text" class="form-control form-control-solid" id="weight" name="weight" rows="1"></input></div>

                <div class="form-group"><label for="favorite">Добавить в топ-меню</label>
                  <div class="custom-control custom-checkbox">
                    <input class="custom-control-input" id="favorite" type="checkbox">
                    <label class="custom-control-label" for="favorite">В топ-меню</label>
                  </div>
                </div>

                <div class="form-group"><label for="sequence_number">Порядковый номер в сортировке</label><input type="text"class="form-control form-control-solid" id="sequence_number" name="sequence_number" rows="1"></input></div>

                <div class="form-group"><label for="status">Статус вывода на экран</label>
                  <div class="custom-control custom-radio custom-control-solid">
                      <input class="custom-control-input" id="status_active" type="radio" name="status">
                      <label class="custom-control-label" for="status_active">Показать</label>
                  </div>
                  <div class="custom-control custom-radio custom-control-solid">
                      <input class="custom-control-input" id="status_disable" type="radio" name="status">
                      <label class="custom-control-label" for="status_disable">Отключить</label>
                  </div>
                  <div class="custom-control custom-radio custom-control-solid">
                      <input class="custom-control-input" id="status_unavailable" type="radio" name="status">
                      <label class="custom-control-label" for="status_unavailable">Недоступен</label>
                  </div>
                </div>

                <div class="form-group"><label for="photo">Фото</label><p><input id="photo" name="photo" type="file"></p></div>
                
                <div class="form-group"><label for="price">Стоимость</label><input type="text" class="form-control form-control-solid" id="price" name="price" rows="1"></input></div>

                <div class="form-group"><label for="category_id">Категория товара</label>
                <p><select name="category_id" style="width: 100%">
                  <optgroup label="Японская кухня">
                   <option value="r1">Закуска Барская</option>
                   <option value="r2">Раки, фаршированные по-царски</option>
                   <option value="r3">Биточки в горшочке</option>
                  </optgroup>
                  <optgroup label="Итальянская кухня">
                   <option value="u1">Галушки славянские</option>
                   <option value="u2">Пампушки украинские</option>
                   <option value="u3">Жаркое по-харьковски</option>
                  </optgroup>
                  <optgroup label="Напитки"></optgroup>
                  <optgroup label="Другие вкусняшки"></optgroup>
                </select></p>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-"></div>
             <button class="btn btn-success btn-block">Отправить</button>
            </div>

          </form>
          <!-- /.container-fluid -->

        </div>
       <!-- End of Main Content -->

      <!-- Footer -->
      <?php require_once ("footer.phtml");?>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <?php require_once ("bottom.phtml"); ?>

</body>

</html>