<?php require_once ("top.phtml"); ?>
<!-- Custom styles for this page -->
  <link href="vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <?php require_once ("menu.phtml");?>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <?php require_once ("header.phtml");?>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800">Tables</h1>
         <!-- <p class="mb-4">
            <?php foreach($errors as $error):?>
              <?php echo $error."<br>";?>
            <?php endforeach;?>
          </p>-->

          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary" style="display: inline-block; line-height: 2.4rem;">Категории товаров</h6>
              <button class="btn btn-primary float-right" onclick="location.href='/?section=admin_products_create';" type="button">Добавить продукт</button>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Название</th>
                      <th>Описание</th>
                      <th>Ингридиенты</th>
                      <th>Вес</th>
                      <th>Ккал</th>
                      <th>Белки</th>
                      <th>Жиры</th>
                      <th>Углеводы</th>
                      <th>Топ-меню</th>
                      <th>Порядковый номер</th>
                      <th>Отображение на сайте</th>
                      <th>Изображение</th>
                      <th>Цена</th>
                      <th>Название категории</th>
                      <th>Операции</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th>ID</th>
                      <th>Название</th>
                      <th>Описание</th>
                      <th>Ингридиенты</th>
                      <th>Вес</th>
                      <th>Ккал</th>
                      <th>Белки</th>
                      <th>Жиры</th>
                      <th>Углеводы</th>
                      <th>Топ-меню</th>
                      <th>Порядковый номер</th>
                      <th>Изображение</th>
                      <th>Цена</th>
                      <th>Название категории</th>
                      <th>Операции</th>
                    </tr>
                  </tfoot>
                  <tbody>
                    <?php foreach ($products as $product): ?>
                    <tr data-id="<?php echo $product['id'];?>"> <!--Пишем data-id чтобы повесить событие-->
                      <td><?php echo $product['id']; ?></td>
                      <td><?php echo $product['name']; ?></td>
                      <td><?php echo $product['comment']; ?></td>
                      <td><?php echo $product['ingredients'];?></td>
                      <td><?php echo $product['weight'];?></td>
                      <td><?php echo $product['kkal'];?></td>
                      <td><?php echo $product['protein'];?></td>
                      <td><?php echo $product['fat'];?></td>
                      <td><?php echo $product['carbo'];?></td>
                      <td><?php echo $product['favorite'] ? 'Да' : 'Нет'; ?></td>
                      <td><?php echo $product['sequence_number'];?></td>
                      <td><?php echo $product['status'];?></td>
                      <td><?php echo $product['photo'];?></td>
                      <td><?php echo $product['price'];?></td>
                      <td><?php echo $product['category_name'];?></td>
                      <td><a href="update"><img src="https://img.icons8.com/bubbles/40/000000/edit.png"/></a>
                        <a href="/?section=admin_categories&operation=delete&id=<?php echo $category['id'];?>"><img src="https://img.icons8.com/bubbles/40/000000/delete-forever.png"/></a>
                        <a name="delete" href="#"><img src="https://img.icons8.com/bubbles/60/000000/delete-forever.png"/></a>
                      </td>
                    </tr>
                  <?php endforeach; ?>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <?php require_once ("footer.phtml");?>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <?php require_once ("bottom.phtml"); ?>

  <!-- Page level plugins -->
  <script src="admin/vendor/datatables/jquery.dataTables.min.js"></script>
  <script src="admin/vendor/datatables/dataTables.bootstrap4.min.js"></script>

  <!-- Page level custom scripts -->
  <script src="admin/js/demo/datatables-demo.js"></script>

  <script>
    $("[name=delete]").click(function (e) {
      e.preventDefault();
      let tr = $(e.target).parents().eq(2);
      let id = tr.data("id"); // e- event - это информация о событии,target-кто вызвал - значок мусорки
      //parents() - строит функцию родителей
      //eq(2) - обращаемся к нужному родителю, учитывая степень вложенности
      //data("id") - считываем id , который находится в параметре data-id

      //Запрос на удаление:
      $.ajax({
        "url": "/?section=admin_categories_delete&id="+id, // +id , который равен $(e.target).parents().eq(2).data("id")
        "method": "GET"
      }).done(function(r) {  // r - response - возвращает всё с admin_categories_delete.route
        console.log(r);
        if (r.status == "error") {
          for (var i = r.messages.length - 1; i >= 0; i--) {
           toastr.error(r.messages[i]);             //toastr - библиотека для вывода сообщений на экран
          }
        } else {
          $(tr).remove(); //JS удаление без перезагрузки из таблицы
          toastr.success("Категория удалена успешно");
        }
      })
      return false; //строка e.preventDefault(); и return false; работают в паре, чтоб не дергалась страница после перехаписи таблицы!!!!!
    });
  </script>

</body>

</html>