<?php require_once("top.phtml"); ?>
</head>
<body>
	<!--[if lte IE 9]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
	<![endif]-->

	<!-- Add your site or application content here -->
	
	<!-- <div class="fakeloader"></div> -->

	<!-- Main wrapper -->
	<div class="wrapper" id="wrapper">
		<?php require_once("header.phtml"); ?>
        <!-- Start Bradcaump area -->
        <div class="ht__bradcaump__area bg-image--29">
            <div class="ht__bradcaump__wrap d-flex align-items-center">
                <div class="slider-text-black container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <div class="bradcaump__inner text-center brad__white">
                                <h2 class="bradcaump-title">О НАС</h2>
                                <nav class="bradcaump-inner">
                                  <a class="breadcrumb-item" href="/?section=index">ГЛАВНАЯ</a>
                                  <span class="brd-separetor"><i class="zmdi zmdi-long-arrow-right"></i></span>
                                  <span class="breadcrumb-item active">О НАС</span>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Bradcaump area -->
        <!-- Start About Us Area  -->
        <section class="food__about__us__area section-padding--lg bg--white">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="section__title title__style--2 service__align--center section__bg__black">
                        <h2 class="title__line">Знакомьтесь - наша команда</h2>
                    </div>
                </div>
            </div>
        </section>
        <!-- End About Us Area  -->
        <!-- Start Our Team Area -->
        <section class="food__team__area team--2 bg--white section-padding--lg bg-image--26">
            <div class="container">
                <div class="row mt--40">
                    <!-- Start Single Team -->
                    <?php foreach ($teams as $team) : ?>
                    <div class="col-lg-4 col-md-4">
                        <div class="team text-center foo">
                            <div class="team__thumb">
                                <a href="team-details.html">
                                    <img src="images/team/team-list/<?php echo $team['photo']; ?>">
                                </a>
                            </div>
                            <div class="team__content">
                                <div class="team__info">
                                    <h4><a href="team-details.html"><?php echo $team['name']; ?></a></h4>
                                    <h6><?php echo $team['position']; ?></h6>
                                </div>
                                <p><?php echo mb_substr($team['comment'], 0,100)."..."; ?></p>
                                <ul class="team__social__net">
                                    <li><a href="#"><i class="zmdi zmdi-google"></i></a></li>
                                    <li><a href="#"><i class="zmdi zmdi-rss"></i></a></li>
                                    <li><a href="#"><i class="zmdi zmdi-tumblr"></i></a></li>
                                    <li><a href="#"><i class="zmdi zmdi-instagram"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                    <!-- End Single Team -->
                </div>
            </div>
        </section>
        <!-- End Our Team Area -->
        <?php require_once("footer.phtml"); ?>
        <?php require_once("login_wrapper.phtml"); ?>
       <?php require_once("cartbox.phtml"); ?>    
	</div>
    <?php require_once("bottom.phtml"); ?>
	
   <!-- <script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')
    </script>-->
</body>
</html>
