<?php require_once("top.phtml"); ?>
</head>
<body>
	<!--[if lte IE 9]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
	<![endif]-->

	<!-- Add your site or application content here -->
	
	<!-- <div class="fakeloader"></div> -->

	<!-- Main wrapper -->
	<div class="wrapper" id="wrapper">
		<?php require_once("header.phtml"); ?>
        <!-- Start Bradcaump area -->
        <div class="ht__bradcaump__area bg-image--18">
            <div class="ht__bradcaump__wrap d-flex align-items-center">
                <div class="slider-text-black container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <div class="bradcaump__inner text-center">
                                <h2 class="bradcaump-title">Блог Details</h2>
                                <nav class="bradcaump-inner">
                                  <a class="breadcrumb-item" href="?/section=index">Главная</a>
                                  <span class="brd-separetor"><i class="zmdi zmdi-long-arrow-right"></i></span>
                                  <span class="breadcrumb-item active">Блог Details</span>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Bradcaump area -->  
        <!-- Start Blog List View Area -->
        <section class="blog__details__wrapper section-padding--lg blog-details-page bg--white">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-12 col-sm-12">
                        <div class="blog__details__container">
                            <div class="bl__dtl__thumb">
                                <img src="images/blog/<?php echo $article['id'];?>/<?php echo $article['image'];?>" alt="big images">
                            </div>
                            <div class="bl__dtl__postmeta d-flex justify-content-between">
                                <ul class="bl__meta d-flex align-items-center">
                                    <li><i class="fa fa-calendar-o"></i><?php echo $created_at;?></li>
                                </ul>
                            </div>
                            <!-- Start Blog Details -->
                            <div class="bl__details__inner">
                                <div class="bl__details__content">
                                    <h2><?php echo $article['title'];?></h2>
                                    <p><?php echo $article['text'];?></p> 
                                    <div class="bl__share d-flex">
                                        <span>Посмотреть информацию в:</span>
                                        <ul class="blog__social__net d-flex">
                                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                            <li><a href="#"><i class="fa fa-google"></i></a></li>
                                            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <!-- Start latest Blog -->
                                <div class="blog__latest__post mb--50">
                                    <h2 class="blog__title">Еще статьи</h2>
                                    <div class="blog__lst__post__wrapper">
                                        <!-- Start Single Post -->
                                        <?php foreach ($related_articles as $ra) :?>
                                            <div class="latest__post__inner">
                                                <div class="latest__post__thumb">
                                                    <a href="/?section=blog_details&article_id=<?php echo $ra['id'];?>">
                                                        <img src="images/blog/<?php echo $ra['id'];?>/<?php echo $ra['image_small'];?>" alt="blog images">
                                                    </a>
                                                </div>
                                                <div class="latest__inner">
                                                    <h6><a href="/?section=blog_details&article_id=<?php echo $ra['id'];?>"><?php echo $ra['title'];?></a></h6>
                                                </div>
                                                <div class="post__hover__inner">
                                                    <div class="post__hover__action">
                                                        <h6><a href="/?section=blog_details&article_id=<?php echo $ra['id'];?>"><?php echo $ra['title'];?></a></h6>
                                                        <span><?php echo \Carbon\Carbon::parse($ra['event_at'])->format('d.m.Y'); ?></span>
                                                        <p><?php echo mb_substr($ra['text'],0,30)."...";?></p>
                                                        <div class="bl__btn">
                                                            <a class="food__btn" href="/?section=blog_details&article_id=<?php echo $ra['id'];?>">Подробнее</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        <?php endforeach;?>
                                        <!-- End Single Post -->
                                    </div>
                                </div>
                                <!-- End latest Blog -->
                            </div>
                            <!-- End Blog Details -->
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-12 col-sm-12 md--mt--40 sm--mt--40">
                        <div class="food__sidebar">
                            <!-- Start Recent Post -->
                            <div class="food__recent__post mt--60">
                                <h4 class="side__title">Еще посты</h4>
                                <div class="recent__post__wrap">
                                    <!-- Start Single Post -->
                                    <?php foreach($related_articles as $ra): ?>
                                        <div class="single__recent__post d-flex">
                                            <div class="recent__post__thumb">
                                                <a href="/?section=blog_details&article_id=<?php echo $ra['id'];?>">
                                                    <img src="images/blog/<?php echo $ra['id'];?>/<?php echo $ra['image_small'];?>" alt="post images">
                                                </a>
                                            </div>
                                            <div class="recent__post__details">
                                                <span><?php echo \Carbon\Carbon::parse($ra['event_at'])->format('d.m.Y'); ?></span>
                                                <h4><a href="/?section=blog_details&article_id=<?php echo $ra['id'];?>"><?php echo $ra['title'];?></a></h4>
                                            </div>
                                        </div>
                                    <?php endforeach; ?>
                                    <!-- End Single Post -->
                                </div>
                            </div>
                            <!-- End Recent Post -->
                            <!-- Start Category Area -->
                           <div class="food__category__area mt--60">
                                <h4 class="side__title">Категории меню</h4>
                                <ul class="food__category">
                                    <?php foreach ($categories as $category) : ?>
                                        <?php if ($category['id'] == ($_GET['category_id'] ?? NULL)) : ?>
                                            <li class="current-active"><?php echo $category['name']; ?></li>
                                        <?php else : ?>
                                            <li><a href="/?section=catalog&category_id=<?php echo $category['id']; ?>"><?php echo $category['name']; ?></a></li>
                                        <?php endif; ?>
                                        <?php if (isset($category['children'])) : ?>
                                                <ul>
                                                <?php foreach ($category['children'] as $child) : ?>
                                                    <?php if ($child['id'] == ($_GET['category_id'] ?? NULL)) : ?>
                                                        <li class="current-active"><?php echo $child['name']; ?><span><?php echo $child['product_count']; ?></span></li>
                                                    <?php else : ?>
                                                        <li><a href="/?section=catalog&category_id=<?php echo $child['id']; ?>"><?php echo $child['name']; ?><span><?php echo $child['product_count']; ?></span></a></li>
                                                    <?php endif; ?>
                                                 <?php endforeach; ?>
                                                 </ul>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                            <!-- End Category Area -->
                            <!-- Start Sidebar Instagram -->
                            <div class="sidebar__instagram mt--60">
                                <h4 class="side__title">Instagram</h4>
                               <iframe src="https://snapwidget.com/embed/846433" class="snapwidget-widget" allowtransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden;  width:255px; height:200px"></iframe>
                            </div>
                            <!-- End Sidebar Instagram -->
                            <!-- Start Sicial NEt -->
                            <div class="sidebar__social__net mt--60">
                                <h4 class="side__title">Социальная сеть</h4>
                                <ul class="var__social__net">
                                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                </ul>
                            </div>
                            <!-- End Sicial NEt -->
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- End Blog List View Area -->
        <?php require_once("footer.phtml"); ?>
        <?php require_once("login_wrapper.phtml"); ?>
        <?php require_once("cartbox.phtml"); ?>  
	</div><!-- //Main wrapper -->

	<?php require_once("bottom.phtml"); ?>

</body>
</html>
