<?php require_once("top.phtml"); ?>
</head>
<body>
	<!--[if lte IE 9]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
	<![endif]-->

	<!-- Add your site or application content here -->
	
	<!-- <div class="fakeloader"></div> -->

	<!-- Main wrapper -->
	<div class="wrapper" id="wrapper">
		<?php require_once("header.phtml"); ?>
        <!-- Start Bradcaump area -->
        <div class="ht__bradcaump__area bg-image--18">
            <div class="ht__bradcaump__wrap d-flex align-items-center">
                <div class="slider-text-black container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <div class="bradcaump__inner text-center">
                                <h2 class="bradcaump-title">Блог Details</h2>
                                <nav class="bradcaump-inner">
                                  <a class="breadcrumb-item" href="?/section=index">Главная</a>
                                  <span class="brd-separetor"><i class="zmdi zmdi-long-arrow-right"></i></span>
                                  <span class="breadcrumb-item active">Блог Details</span>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Bradcaump area -->  
        <!-- Start Blog List View Area -->
        <section class="blog__details__wrapper section-padding--lg blog-details-page bg--white">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-12 col-sm-12">
                        <div class="blog__details__container">
                            <div class="bl__dtl__thumb">
                                <img src="images/blog/details/1.jpg" alt="big images">
                            </div>
                            <div class="bl__dtl__postmeta d-flex justify-content-between">
                                <ul class="bl__meta d-flex align-items-center">
                                    <li><i class="fa fa-user-o"></i>Posted By: <a href="#">Admin</a></li>
                                    <li><i class="fa fa-calendar-o"></i>February  13,  2018</li>
                                </ul>
                                <ul class="bl__like__comment d-flex">
                                    <li><a href="#"><i class="fa fa-comment-o"></i>05</a></li>
                                    <li><a href="#"><i class="fa fa-heart-o"></i>07</a></li>
                                </ul>
                            </div>
                            <!-- Start Blog Details -->
                            <div class="bl__details__inner">
                                <div class="bl__details__content">
                                    <span>Category : Pasta</span>
                                    <h2>standard blog post format for Design.</h2>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labor dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ualiqui comi modo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillumfugiat nu pariatur.Excepteur sint occaecat cupidatat non proident,</p>
                                    <ul class="food__sm__blog d-flex">
                                        <li><a href="#"><img src="images/blog/details/2.jpg" alt="blog images"></a></li>
                                        <li><a href="#"><img src="images/blog/details/3.jpg" alt="blog images"></a></li>
                                    </ul>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labor dolore magna aliqua. Ut enim  minim veniam, “quis nostrud exercitation ullamco laboris nisi ut aliqui ”modo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillumfugiat nu pariatur.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,</p>
                                    <blockquote>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris ahj</blockquote> 
                                    <p>Est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.</p> 
                                    <div class="rel__blog__list d-flex align-items-start justify-content-between">
                                        <ul class="sm__bl__list">
                                            <li><a href="#">Duis aute irure dolor in reprehenderit in voluptat</a></li>
                                            <li><a href="#">Duis aute irure dolor in reprehenderit in voluptat</a></li>
                                            <li><a href="#">Duis aute irure dolor in reprehenderit in voluptat</a></li>
                                            <li><a href="#">Duis aute irure dolor in reprehenderit in voluptat</a></li>
                                            <li><a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing</a></li>
                                        </ul>
                                        <div class="sm__blog__thumb">
                                            <a href="#">
                                                <img src="images/blog/details/4.jpg" alt="blog images">
                                            </a>
                                        </div>
                                    </div>
                                    <p>o consequat. Duis aute irure dolor in reprehenderit in voluptate vel  cillumfugiat pariatur.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunmollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptat accusantium doloremque st laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptaccusantium doloremquequisquam est, qui dolorem ipsum quia dolor sit ametquaerat voluptatem.</p>
                                    <div class="bl__share d-flex">
                                        <span>Share by:</span>
                                        <ul class="blog__social__net d-flex">
                                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                            <li><a href="#"><i class="fa fa-google"></i></a></li>
                                            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <!-- Start Blog Author -->
                                <div class="blog__author">
                                    <h2 class="blog__title">about author</h2>
                                    <div class="food__author d-flex flex-wrap flex-lg-nowrap flex-md-nowrap">
                                        <div class="author__thumb">
                                            <img src="images/blog/details/5.jpg" alt="author images">
                                        </div>
                                        <div class="author__details">
                                            <h2><a href="#">Robart Hanson</a></h2>
                                            <div class="author__meta d-flex justify-content-between">
                                                <span>Admin - February  13,  2018</span>
                                                <ul class="rating d-flex">
                                                    <li><i class="zmdi zmdi-star"></i></li>
                                                    <li><i class="zmdi zmdi-star"></i></li>
                                                    <li><i class="zmdi zmdi-star"></i></li>
                                                    <li><i class="zmdi zmdi-star"></i></li>
                                                    <li><i class="zmdi zmdi-star"></i></li>
                                                </ul>
                                            </div>
                                            <p>Lorem ipsum dolor sit amet, consectetur adip icinelit,tdom ineiusd tempor incididunt ut labore et dolore magna aliqua. Ut e veniam, nostrud exercitation ullamco laboris nisi ut aliquiconsequat.</p>
                                            <ul class="author__link d-flex">
                                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                                <li><a href="#"><i class="fa fa-google"></i></a></li>
                                                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Blog Author -->
                                <!-- Start latest Blog -->
                                <div class="blog__latest__post mb--50">
                                    <h2 class="blog__title">latest blog</h2>
                                    <div class="blog__lst__post__wrapper">
                                        <!-- Start Single Post -->
                                        <div class="latest__post__inner">
                                            <div class="latest__post__thumb">
                                                <a href="#">
                                                    <img src="images/blog/details/6.jpg" alt="blog images">
                                                </a>
                                            </div>
                                            <div class="latest__inner">
                                                <h6><a href="blog-details.html">CHicken Fry</a></h6>
                                            </div>
                                            <div class="post__hover__inner">
                                                <div class="post__hover__action">
                                                    <h6><a href="blog.details.html">CHicken Fry</a></h6>
                                                    <span>1st Oct, 2o17</span>
                                                    <p>ipsum doit amadi pisicing elit, seddo eiusmoddolnisi.</p>
                                                    <div class="bl__btn">
                                                        <a class="food__btn" href="blog-details.html">Read More</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- End Single Post -->
                                        <!-- Start Single Post -->
                                        <div class="latest__post__inner">
                                            <div class="latest__post__thumb">
                                                <a href="#">
                                                    <img src="images/blog/details/7.jpg" alt="blog images">
                                                </a>
                                            </div>
                                            <div class="latest__inner">
                                                <h6><a href="blog-details.html">CHicken Fry</a></h6>
                                            </div>
                                            <div class="post__hover__inner">
                                                <div class="post__hover__action">
                                                    <h6><a href="blog.details.html">CHicken Fry</a></h6>
                                                    <span>1st Oct, 2o17</span>
                                                    <p>ipsum doit amadi pisicing elit, seddo eiusmoddolnisi.</p>
                                                    <div class="bl__btn">
                                                        <a class="food__btn" href="blog-details.html">Read More</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- End Single Post -->
                                        <!-- Start Single Post -->
                                        <div class="latest__post__inner">
                                            <div class="latest__post__thumb">
                                                <a href="#">
                                                    <img src="images/blog/details/8.jpg" alt="blog images">
                                                </a>
                                            </div>
                                            <div class="latest__inner">
                                                <h6><a href="blog-details.html">Pan Cake</a></h6>
                                            </div>
                                            <div class="post__hover__inner">
                                                <div class="post__hover__action">
                                                    <h6><a href="blog.details.html">Pan Cake</a></h6>
                                                    <span>1st Oct, 2o17</span>
                                                    <p>ipsum doit amadi pisicing elit, seddo eiusmoddolnisi.</p>
                                                    <div class="bl__btn">
                                                        <a class="food__btn" href="blog-details.html">Read More</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- End Single Post -->
                                    </div>
                                </div>
                                <!-- End latest Blog -->
                                <!-- Start Blog Comment -->
                                <div class="blog__comment__wrapper">
                                    <h2 class="blog__title">comment’s</h2>
                                    <div class="blog__comment__inner">
                                        <!-- Start Single Comment -->
                                        <div class="comment d-flex flex-wrap flex-md-nowrap flex-lg-nowrap">
                                            <div class="commnet__thumb">
                                                <img src="images/comment/1.jpg" alt="comment images">
                                            </div>
                                            <div class="comment__details">
                                                <h5>Robart Hanson</h5>
                                                <div class="cmment__date d-flex justify-content-between">
                                                    <span>February  13,  2018</span>
                                                    <ul class="rating d-flex">
                                                        <li><i class="zmdi zmdi-star"></i></li>
                                                        <li><i class="zmdi zmdi-star"></i></li>
                                                        <li><i class="zmdi zmdi-star"></i></li>
                                                        <li><i class="zmdi zmdi-star"></i></li>
                                                        <li><i class="zmdi zmdi-star"></i></li>
                                                    </ul>
                                                </div>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipis icing incididunt labore et dolore magna aliqua. Ut enim adm veniam, quis nostrud exercitation.</p>
                                                <ul class="reply__btn d-flex justify-content-start justify-content-md-end justify-content-lg-end">
                                                    <li><a href="#"><i class="fa fa-reply"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-angle-up"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-angle-down"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <!-- End Single Comment -->
                                        <!-- Start Single Comment -->
                                        <div class="comment d-flex flex-wrap flex-md-nowrap flex-lg-nowrap comment__reply">
                                            <div class="commnet__thumb">
                                                <img src="images/comment/2.jpg" alt="comment images">
                                            </div>
                                            <div class="comment__details">
                                                <h5>Irin Pervin</h5>
                                                <div class="cmment__date d-flex justify-content-between">
                                                    <span>February  13,  2018</span>
                                                    <ul class="rating d-flex">
                                                        <li><i class="zmdi zmdi-star"></i></li>
                                                        <li><i class="zmdi zmdi-star"></i></li>
                                                        <li><i class="zmdi zmdi-star"></i></li>
                                                        <li><i class="zmdi zmdi-star"></i></li>
                                                        <li><i class="zmdi zmdi-star"></i></li>
                                                    </ul>
                                                </div>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipis icing incididunt labore et dolore magna aliqua. Ut enim adm veniam, quis nostrud exercitation.</p>
                                                <ul class="reply__btn d-flex justify-content-start justify-content-md-end justify-content-lg-end">
                                                    <li><a href="#"><i class="fa fa-reply"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-angle-up"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-angle-down"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <!-- End Single Comment -->
                                        <!-- Start Single Comment -->
                                        <div class="comment d-flex flex-wrap flex-md-nowrap flex-lg-nowrap">
                                            <div class="commnet__thumb">
                                                <img src="images/comment/3.jpg" alt="comment images">
                                            </div>
                                            <div class="comment__details">
                                                <h5>Najnin Supa</h5>
                                                <div class="cmment__date d-flex justify-content-between">
                                                    <span>February  13,  2018</span>
                                                    <ul class="rating d-flex">
                                                        <li><i class="zmdi zmdi-star"></i></li>
                                                        <li><i class="zmdi zmdi-star"></i></li>
                                                        <li><i class="zmdi zmdi-star"></i></li>
                                                        <li><i class="zmdi zmdi-star"></i></li>
                                                        <li><i class="zmdi zmdi-star"></i></li>
                                                    </ul>
                                                </div>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipis icing incididunt labore et dolore magna aliqua. Ut enim adm veniam, quis nostrud exercitation.</p>
                                                <ul class="reply__btn d-flex justify-content-start justify-content-md-end justify-content-lg-end">
                                                    <li><a href="#"><i class="fa fa-reply"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-angle-up"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-angle-down"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <!-- End Single Comment -->
                                    </div>
                                </div>
                                <!-- End Blog Comment -->
                                <!-- Start Comment Form -->
                                <div class="blog__comment__form">
                                    <h2 class="blog__title">leave A Comment</h2>
                                    <div class="comment__form">
                                        <div class="ct__form__box d-flex flex-wrap flex-lg-nowrap flex-md-nowrap">
                                            <input type="text" placeholder="First name *">
                                            <input type="text" placeholder="Last Name *">
                                        </div>
                                        <div class="ct__form__box d-flex flex-wrap flex-lg-nowrap flex-md-nowrap">
                                            <input type="email" placeholder="E-mail *">
                                            <input type="text" placeholder="Phone *">
                                        </div>
                                        <div class="ct__form__box">
                                            <textarea name="message" placeholder="Your Message"></textarea>
                                        </div>
                                        <div class="comment__btn">
                                            <a class="food__btn" href="#">submit</a>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Comment Form -->
                            </div>
                            <!-- End Blog Details -->
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-12 col-sm-12 md--mt--40 sm--mt--40">
                        <div class="food__sidebar">
                            <div class="side__bl__inner">
                                <div class="side__bl__thumb">
                                    <img src="images/blog/sidebar/1.jpg" alt="sidebar images">
                                </div>
                                <div class="side__bl__details">
                                    <p>On the other hand, dislike men who are so beguiled and demoralized by the charms of pleasure of the moment.</p>
                                    <h4>Robart Rofiq Bali</h4>
                                    <h6>UI UX Designer</h6>
                                    <ul class="bl__social__service d-flex">
                                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                        <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
                                        <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <!-- Start Search Area -->
                            <div class="food__search mt--60">
                                <h4 class="side__title">Search</h4>
                                <div class="serch__box">
                                    <input type="text" placeholder="Search keyword">
                                    <a href="#"><i class="fa fa-search"></i></a>
                                </div>
                            </div>
                            <!-- End Search Area -->
                            <!-- Start Recent Post -->
                            <div class="food__recent__post mt--60">
                                <h4 class="side__title">Recent Posts</h4>
                                <div class="recent__post__wrap">
                                    <!-- Start Single Post -->
                                    <div class="single__recent__post d-flex">
                                        <div class="recent__post__thumb">
                                            <a href="blog-details.html">
                                                <img src="images/blog/sm-img/4.jpg" alt="post images">
                                            </a>
                                        </div>
                                        <div class="recent__post__details">
                                            <span>February  13,  2018</span>
                                            <h4><a href="blog-details.html">Diffrent title gose here. This is demo title.</a></h4>
                                        </div>
                                    </div>
                                    <!-- End Single Post -->
                                    <!-- Start Single Post -->
                                    <div class="single__recent__post d-flex">
                                        <div class="recent__post__thumb">
                                            <a href="blog-details.html">
                                                <img src="images/blog/sm-img/5.jpg" alt="post images">
                                            </a>
                                        </div>
                                        <div class="recent__post__details">
                                            <span>February  13,  2018</span>
                                            <h4><a href="blog-details.html">Diffrent title gose here. This is demo title.</a></h4>
                                        </div>
                                    </div>
                                    <!-- End Single Post -->
                                    <!-- Start Single Post -->
                                    <div class="single__recent__post d-flex">
                                        <div class="recent__post__thumb">
                                            <a href="blog-details.html">
                                                <img src="images/blog/sm-img/6.jpg" alt="post images">
                                            </a>
                                        </div>
                                        <div class="recent__post__details">
                                            <span>February  13,  2018</span>
                                            <h4><a href="blog-details.html">Diffrent title gose here. This is demo title.</a></h4>
                                        </div>
                                    </div>
                                    <!-- End Single Post -->
                                    <!-- Start Single Post -->
                                    <div class="single__recent__post d-flex">
                                        <div class="recent__post__thumb">
                                            <a href="blog-details.html">
                                                <img src="images/blog/sm-img/7.jpg" alt="post images">
                                            </a>
                                        </div>
                                        <div class="recent__post__details">
                                            <span>February  13,  2018</span>
                                            <h4><a href="blog-details.html">Diffrent title gose here. This is demo title.</a></h4>
                                        </div>
                                    </div>
                                    <!-- End Single Post -->
                                </div>
                            </div>
                            <!-- End Recent Post -->
                            <!-- Start Category Area -->
                            <div class="food__category__area mt--60">
                                <h4 class="side__title">Categories</h4>
                                <ul class="food__category">
                                    <li><a href="#">Asian Twist <span>(20)</span></a></li>
                                    <li><a href="#">Pizza <span>(30)</span></a></li>
                                    <li><a href="#">Food & Beverage <span>(40)</span></a></li>
                                    <li><a href="#">Maxican Food <span>(50)</span></a></li>
                                    <li><a href="#">Asian Twist <span>(60)</span></a></li>
                                    <li><a href="#">Taco Food <span>(20)</span></a></li>
                                </ul>
                            </div>
                            <!-- End Category Area -->
                            <!-- Start Recent Comment -->
                            <div class="food__recent__comment mt--60">
                                <h4 class="side__title">Recent Comment</h4>
                                <div class="food__comment">
                                    <!-- Start Single Comment -->
                                    <div class="single__comment">
                                        <h2><i class="fa fa-comments-o"></i><a href="#">Creative Design for blog post. Its also simple.</a></h2>
                                        <ul class="comment__meta">
                                            <li>13 Feb 2016</li>
                                            <li><a href="#">04.00am</a></li>
                                            <li><a href="#">Arif Vai</a></li>
                                        </ul>
                                    </div>
                                    <!-- End Single Comment -->
                                    <!-- Start Single Comment -->
                                    <div class="single__comment">
                                        <h2><i class="fa fa-comments-o"></i><a href="#">Creative Design for blog post. Its also simple.</a></h2>
                                        <ul class="comment__meta">
                                            <li>13 Feb 2016</li>
                                            <li><a href="#">04.00am</a></li>
                                            <li><a href="#">Arif Vai</a></li>
                                        </ul>
                                    </div>
                                    <!-- End Single Comment -->
                                    <!-- Start Single Comment -->
                                    <div class="single__comment">
                                        <h2><i class="fa fa-comments-o"></i><a href="#">Creative Design for blog post.</a></h2>
                                        <ul class="comment__meta">
                                            <li>13 Feb 2016</li>
                                            <li><a href="#">04.00am</a></li>
                                            <li><a href="#">Arif Vai</a></li>
                                        </ul>
                                    </div>
                                    <!-- End Single Comment -->
                                    <!-- Start Single Comment -->
                                    <div class="single__comment">
                                        <h2><i class="fa fa-comments-o"></i><a href="#">Creative Design for blog post. Its also simple.</a></h2>
                                        <ul class="comment__meta">
                                            <li>13 Feb 2016</li>
                                            <li><a href="#">04.00am</a></li>
                                            <li><a href="#">Arif Vai</a></li>
                                        </ul>
                                    </div>
                                    <!-- End Single Comment -->
                                    <!-- Start Single Comment -->
                                    <div class="single__comment">
                                        <h2><i class="fa fa-comments-o"></i><a href="#">Creative Design for blog post.</a></h2>
                                        <ul class="comment__meta">
                                            <li>13 Feb 2016</li>
                                            <li><a href="#">04.00am</a></li>
                                            <li><a href="#">Arif Vai</a></li>
                                        </ul>
                                    </div>
                                    <!-- End Single Comment -->
                                </div>
                            </div>
                            <!-- End Recent Comment -->
                            <!-- Start Sidebar Contact -->
                            <div class="sidebar__contact mt--60">
                                <div class="sidebar__thumb">
                                    <img src="images/blog/sidebar/2.jpg" alt="sidebar images">
                                </div>
                                <div class="sidebar__details">
                                    <h4>colorful</h4>
                                    <h2>donut’s</h2>
                                    <span>get it till the stock full</span>
                                </div>
                                <div class="sidebar__con__btn">
                                    <a href="#">Contact Now<i class="fa fa-long-arrow-right"></i></a>
                                </div>
                            </div>
                            <!-- End Sidebar Contact -->
                            <!-- Start Sidebar Newsletter -->
                            <div class="sidebar__newsletter mt--60">
                                <h4 class="side__title">Newsletter</h4>
                                <div class="sidebar__inbox">
                                    <input type="text" placeholder="Enter your E-mail">
                                    <a href="#"><i class="fa fa-paper-plane"></i></a>
                                </div>
                            </div>
                            <!-- End Sidebar Newsletter -->
                            <!-- Start Sidebar Instagram -->
                            <div class="sidebar__instagram mt--60">
                                <h4 class="side__title">Instagram</h4>
                                <ul class="instagram__list d-flex flex-wrap">
                                    <li><a href="#"><img src="images/blog/instagram/1.jpg" alt="instagram images"></a></li>
                                    <li><a href="#"><img src="images/blog/instagram/2.jpg" alt="instagram images"></a></li>
                                    <li><a href="#"><img src="images/blog/instagram/3.jpg" alt="instagram images"></a></li>
                                    <li><a href="#"><img src="images/blog/instagram/4.jpg" alt="instagram images"></a></li>
                                    <li><a href="#"><img src="images/blog/instagram/5.jpg" alt="instagram images"></a></li>
                                    <li><a href="#"><img src="images/blog/instagram/6.jpg" alt="instagram images"></a></li>
                                </ul>
                            </div>
                            <!-- End Sidebar Instagram -->
                            <!-- Start twitter Feed -->
                            <div class="sidebar__twitter mt--60">
                                <h4 class="side__title">Recent Tweets</h4>
                                <div class="twitter__wrap">
                                    <div class="recent__twitter">
                                        <h6><a href="#"><i class="fa fa-twitter"></i>@momenbhuiyan</a></h6>
                                        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
                                        <ul class="twit__meta">
                                            <li>13 Feb 2016</li>
                                            <li>04.00am</li>
                                        </ul>
                                    </div>
                                    <div class="recent__twitter">
                                        <h6><a href="#"><i class="fa fa-twitter"></i>@momenbhuiyan</a></h6>
                                        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
                                        <ul class="twit__meta">
                                            <li>13 Feb 2016</li>
                                            <li>04.00am</li>
                                        </ul>
                                    </div>
                                    <div class="recent__twitter">
                                        <h6><a href="#"><i class="fa fa-twitter"></i>@momenbhuiyan</a></h6>
                                        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
                                        <ul class="twit__meta">
                                            <li>13 Feb 2016</li>
                                            <li>04.00am</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <!-- End twitter Feed -->
                            <!-- Start Sicial NEt -->
                            <div class="sidebar__social__net mt--60">
                                <h4 class="side__title">Social Network</h4>
                                <ul class="var__social__net">
                                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                </ul>
                            </div>
                            <!-- End Sicial NEt -->
                            <!-- Start Tag Area -->
                            <div class="food__tag mt--60">
                                <h4 class="side__title">Tags</h4>
                                <ul class="tag__list d-flex flex-wrap">
                                    <li><a href="#">Pizza</a></li>
                                    <li><a href="#">Chicken</a></li>
                                    <li><a href="#">Adobe</a></li>
                                    <li><a href="#">Beef Swarma</a></li>
                                    <li><a href="#">Pasta</a></li>
                                    <li><a href="#">Burger</a></li>
                                </ul>
                            </div>
                            <!-- End Tag Area -->
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- End Blog List View Area -->
        <?php require_once("footer.phtml"); ?>
        <?php require_once("login_wrapper.phtml"); ?>
        <?php require_once("cartbox.phtml"); ?>  
	</div><!-- //Main wrapper -->

	<?php require_once("bottom.phtml"); ?>

</body>
</html>
