<!-- JS Files -->
    <script src="js/vendor/jquery-3.2.1.min.js"></script>
    <script src="js/popper.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/plugins.js"></script>
    <script src="js/active.js"></script>
    <script src="js/functions.js"></script>
    <script type="text/javascript">
    	$(document).ready(function() {
    		cart_box_render();
            $(document).on("click", ".cartbox__item__remove", function(e) {
                var product_id = $(this).parent().data("product_id");
                $.ajax({
                    url:"/?section=remove_from_cart",
                    method: "POST",
                    data: {
                        "product_id": product_id
                    }
                }).done(function(r) {
                    if (r.data !== undefined) {
                        cart_box_render();
                    }
                })
            })
    	});
    </script>

  