<?php require_once("top.phtml"); ?>
</head>
<body>
	<!--[if lte IE 9]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
	<![endif]-->

	<!-- Add your site or application content here -->
	
	<!-- <div class="fakeloader"></div> -->

	<!-- Main wrapper -->
	<div class="wrapper" id="wrapper">
		<?php require_once("header.phtml"); ?>
        <!-- Start Bradcaump area -->
        <div class="ht__bradcaump__area bg-image--30">
            <div class="ht__bradcaump__wrap d-flex align-items-center">
                <div class="slider-text-black container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <div class="bradcaump__inner text-center">
                                <h2 class="bradcaump-title">Меню ФУД-Экспресс</h2>
                                <nav class="bradcaump-inner">
                                  <a class="breadcrumb-item" href="/?section=index">Главная</a>
                                  <span class="brd-separetor"><i class="zmdi zmdi-long-arrow-right"></i></span>
                                  <span class="breadcrumb-item active">Каталог</span>
                                  <?php if (isset($current_category['id'])) : ?>
                                      <span class="brd-separetor"><i class="zmdi zmdi-long-arrow-right"></i></span>
                                      <span class="breadcrumb-item active"><?php echo $current_category['name']; ?></span>
                                  <?php else : ?><span>&nbsp;</span>
                                  <?php endif; ?>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Bradcaump area --> 
        <!-- Start Menu Grid Area -->
        <section class="food__menu__grid__area section-padding--lg" style="padding-left: 50px; padding-right: 50px; padding-top: 0px;">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <!-- Start Tag Area -->
                            <div class="food__tag mt--60">
                                <h4 class="side__title">Теги</h4>
                                <ul class="tag__list d-flex flex-wrap">
                                        <?php foreach ($tags as $tag) : ?>
                                        <li><a href="/?section=catalog&tag_id=<?php echo $tag['id'] ?>"><?php echo $tag['name']; ?></a></li>
                                        <?php endforeach; ?>
                                </ul>
                            </div>
                            <!-- End Tag Area -->
                    </div>
                </div>
                <div class="row mt--30">
                    <div class="col-lg-3 col-md-12 col-sm-12 md--mt--40 sm--mt--40">
                        <div class="food__sidebar">
                             <!-- Start Category Area -->
                            <div class="food__category__area mt--60">
                                <h4 class="side__title">Категории меню</h4>
                                <ul class="food__category">
                                    <?php foreach ($categories as $category) : ?>
                                        <?php if ($category['id'] == ($_GET['category_id'] ?? NULL)) : ?>
                                            <li class="current-active"><?php echo $category['name']; ?></li>
                                        <?php else : ?>
                                            <li><a href="/?section=catalog&category_id=<?php echo $category['id']; ?>"><?php echo $category['name']; ?></a></li>
                                        <?php endif; ?>
                                        <?php if (isset($category['children'])) : ?>
                                                <ul>
                                                <?php foreach ($category['children'] as $child) : ?>
                                                    <?php if ($child['id'] == ($_GET['category_id'] ?? NULL)) : ?>
                                                        <li class="current-active"><?php echo $child['name']; ?><span><?php echo $child['product_count']; ?></span></li>
                                                    <?php else : ?>
                                                        <li><a href="/?section=catalog&category_id=<?php echo $child['id']; ?>"><?php echo $child['name']; ?><span><?php echo $child['product_count']; ?></span></a></li>
                                                    <?php endif; ?>
                                                 <?php endforeach; ?>
                                                 </ul>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                            <!-- End Category Area -->
                            <!-- Start Search Area -->
                            <div class="food__search mt--60">
                                <h4 class="side__title">Search</h4>
                                <div class="serch__box">
                                    <input type="text" placeholder="Search keyword">
                                    <a href="#"><i class="fa fa-search"></i></a>
                                </div>
                            </div>
                            <!-- End Search Area -->
                             <!-- Start Sidebar Instagram -->
                            <div class="sidebar__instagram mt--60">
                                <h4 class="side__title">Instagram</h4>
                                <!-- SnapWidget -->
<iframe src="https://snapwidget.com/embed/846433" class="snapwidget-widget" allowtransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden;  width:290px; height:435px"></iframe>
                            </div>
                            <!-- End Sidebar Instagram -->
                            <?php include("../templates/widgets/recent_post.widget.phtml"); ?>
                            <!-- Start Sidebar Contact -->
                            <div class="sidebar__contact mt--60">
                                <div class="sidebar__thumb">
                                    <img src="images/blog/sidebar/2.jpg" alt="sidebar images">
                                </div>
                                <div class="sidebar__details">
                                    <h4>colorful</h4>
                                    <h2>donut’s</h2>
                                    <span>get it till the stock full</span>
                                </div>
                                <div class="sidebar__con__btn">
                                    <a href="#">Contact Now<i class="fa fa-long-arrow-right"></i></a>
                                </div>
                            </div>
                            <!-- End Sidebar Contact -->
                            <!-- Start Sicial NEt -->
                            <div class="sidebar__social__net mt--60">
                                <h4 class="side__title">Social Network</h4>
                                <ul class="var__social__net">
                                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                </ul>
                            </div>
                            <!-- End Sicial NEt -->
                        </div>
                    </div>
                    <div class="col-lg-9">
                        <div class="fd__tab__content tab-content" id="nav-tabContent">
                            <!-- Start Single Content -->
                            <div class="food__list__tab__content tab-pane fade show active" id="nav-all" role="tabpanel">
                                <!-- Start Single Food -->
                                <?php foreach ($products as $product) : ?>
                                    <div class="single__food__list d-flex wow fadeInUp">
                                        <div class="food__list__thumb">
                                            <a href="/?section=menu_details&product_id=<?php echo $product['id']; ?>">
                                                <img src="images/product/<?php echo $product['id'].'/'.$product['photo']; ?>">
                                            </a>
                                        </div>
                                        <div class="food__list__inner d-flex align-items-center justify-content-between">
                                            <div class="food__list__details">
                                                <h2><a href="/?section=menu_details&product_id=<?php echo $product['id']; ?>"><?php echo $product['name']; ?></a></h2>
                                                <?php if (!is_null($product['weight'])) : ?>
                                                    <p><img src="https://img.icons8.com/ios-glyphs/16/000000/scales.png"/>&nbsp;<b>Вес:</b> <?php echo $product['weight']; ?> г <br>
                                                <?php else : ?> <p>&nbsp;</p>
                                                <?php endif; ?>  
                                                <?php if (!is_null($product['kkal'])) : ?> 
                                                     <img src="https://img.icons8.com/android/16/000000/flex-biceps.png"/>&nbsp;<b>Энергоценность:</b> <?php echo $product['kkal']; ?> ккал <br>
                                                <?php else : ?> <p>&nbsp;</p>
                                                <?php endif; ?>
                                                <?php if (!is_null($product['ingredients'])) : ?>
                                                     <img src="https://img.icons8.com/material-outlined/16/000000/align-cell-content-top.png"/>&nbsp;
                                                    <b>Состав:</b> <?php echo @implode(', ', json_decode($product['ingredients'])); ?>
                                                <?php endif; ?>

                                                <div class="list__btn">
                                                    <a class="food__btn grey--btn theme--hover" href="/?section=menu_details&product_id=<?php echo $product['id'] ; ?>">ПОДРОБНЕЕ</a>
                                                </div>
                                            </div>
                                            <div class="food__rating">
                                                <div class="list__food__prize">
                                                    <span><?php echo $product['price']; ?>&#8381;</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                               <?php endforeach; ?>
                                <!-- End Single Food -->
                            </div>
                            <!-- End Single Content -->
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="food__pagination d-flex justify-content-center align-items-center mt--130">
                            <li><a href="/?<?php echo $build_query.'&page=1'; ?>"><i class="zmdi zmdi-chevron-left"></i></a></li>
                            <?php for ($i = 1; $i <= $page_count; $i++) : ?>
                                <?php $class = $i == $page ? "active" : ""; ?>
                                <li class="<?php echo $class; ?>"><a href="/?<?php echo $build_query.'&page='.$i; ?>"><?php echo $i; ?></a></li>
                            <?php endfor; ?>
                            <li><a href="/?<?php echo $build_query.'&page='.$page_count; ?>"><i class="zmdi zmdi-chevron-right"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
        <!-- End Menu Grid Area -->
        <?php require_once("footer.phtml"); ?>
       <?php require_once("login_wrapper.phtml"); ?>
        <?php require_once("cartbox.phtml"); ?>  
	</div><!-- //Main wrapper -->

    <?php require_once("bottom.phtml"); ?>
</body>
</html>
