<?php  require_once("top.phtml"); ?>
</head>
<body>
    <!--[if lte IE 9]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
    <![endif]-->

    <!-- Add your site or application content here -->
    
    <!-- <div class="fakeloader"></div> -->

    <!-- Main wrapper -->
    <div class="wrapper" id="wrapper">
        <!-- Start Header Area -->
        <?php require_once("header.phtml"); ?>
        <!-- End Header Area -->
        <!-- Start Bradcaump area -->
        <div class="ht__bradcaump__area bg-image--18">
            <div class="ht__bradcaump__wrap d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <div class="bradcaump__inner text-center">
                                <h2 class="bradcaump-title">Оформить заказ</h2>
                                <nav class="bradcaump-inner">
                                  <a class="breadcrumb-item" href="/?section=index">Главня</a>
                                  <span class="brd-separetor"><i class="zmdi zmdi-long-arrow-right"></i></span>
                                  <span class="breadcrumb-item active">Оформить заказ</span>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Bradcaump area --> 
         <section class="htc__checkout bg--white section-padding--lg">
            <!-- Checkout Section Start-->
            <div class="checkout-section">
                <div class="container">
                    <div class="row">
                          
                        <div class="col-lg-6 col-12 mb-30">
                            <form action="" method="POST" class="billing-form checkout-form">    
                                    <!-- Checkout Accordion Start -->
                                <div id="checkout-accordion"> 
                                    <!-- Billing Method -->
                                    
                                    <div class="single-accordion">
                                        <a class="accordion-head collapsed" data-toggle="collapse" data-parent="#checkout-accordion" href="#billing-method">1. Платежная информация</a>
                                        <div id="billing-method" class="collapse show">

                                            <div class="accordion-body billing-method fix">
                                                <div class="row">
                                                    <div class="col-md-6 col-12 mb--20">                                 
                                                        <input type="text" name="client_name" value="<?php echo @$_POST['client_name'];?>" placeholder="Как Вас зовут *">
                                                        <?php if (isset($errors['client_name'])) : ?>
                                                            <label id="client_name-error" class="error" for="client_name"><?php echo $errors['client_name']; ?></label>
                                                        <?php endif; ?>
                                                    </div>
                                                    <div class="col-md-6 col-12">                                   
                                                        <input type="text" name="client_phone" value="<?php echo @$_POST['client_phone'];?>" placeholder="Номер телефона *">
                                                        <?php if(isset($errors['client_phone'])) : ?>
                                                            <label id="client_phone-error" class="error" for="client_phone">
                                                            <?php echo $errors['client_phone']; ?></label>
                                                        <?php endif; ?>
                                                    </div> 
                                                    <div class="col-12 mb--20">
                                                        <select name="addr_city">
                                                          <!--<option value="0" selected disabled>Ваш город *</option>
                                                          <option value="<?php echo @$_POST['addr_city'];?>">Севастополь</option>
                                                          <option value="Симферополь">Симферополь</option>-->
                                                          <option selected disabled>Ваш город *</option>
                                                          <?php foreach ($addr_city as $value):?>
                                                            <?php $selected = @$_POST['addr_city'] == $value ? 'selected' : ''; ?>
                                                            <option <?php echo $selected;?> value="<?php echo $value;?>"><?php echo $value; ?></option>
                                                          <?php endforeach; ?>
                                                        </select>
                                                        <?php if (isset($errors['addr_city'])) : ?>
                                                            <label id="addr_city-error" class="error" for="addr_city">
                                                            <?php echo $errors['addr_city']; ?></label>
                                                        <?php endif; ?>
                                                    </div>
                                                    <div class="col-12 mb--20">
                                                        <input type="text" name="addr_street" value="<?php echo @$_POST['addr_street']; ?>" placeholder="Улица/Проспект *">
                                                        <?php if (isset($errors['addr_street'])) : ?>
                                                            <label id="addr_street-error" class="error" for="addr_street"><?php echo $errors['addr_street']; ?></label>
                                                        <?php endif; ?>
                                                    </div>
                                                    <div class="col-md-4 mb--20">
                                                        <input type="text" name="addr_build" value="<?php echo @$_POST['addr_build']; ?>" placeholder="Дом *" >
                                                        <?php if (isset($errors['addr_build'])) : ?>
                                                            <label id="addr_build-error" class="error" for="addr_build"><?php echo $errors['addr_build']; ?></label>
                                                        <?php endif; ?>
                                                    </div>
                                                    <div class="col-md-4 mb--20">
                                                        <input type="text" name="addr_flat" value="<?php echo @$_POST['addr_flat']; ?>" placeholder="Квартира">
                                                    </div>
                                                    <div class="col-md-4 col-12 mb--20">                                 
                                                        <input type="text" name="addr_domophone_code" value="<?php echo @$_POST['addr_domophone_code']; ?>" placeholder="Домофон">
                                                    </div>  
                                                    <div style="color: red">
                                                        Поля со звездочкой * ОБЯЗАТЕЛЬНЫ к заполнению
                                                    </div>                                
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <!-- Shipping Method -->
                                    <div class="single-accordion">
                                        <a class="accordion-head collapsed" data-toggle="collapse" data-parent="#checkout-accordion" href="#shipping-method">2. Информация о заказе</a>
                                        <div id="shipping-method" class="collapse show">
                                            <div class="accordion-body shipping-method fix">
                                                <div class="col-12 col-12 mb--20">                                 
                                                  <label for="in_time">
                                                        К какому времени доставить заказ?
                                                  </label><br>
                                                  <select name="in_time" id="in_time">
                                                    <option disabled selected>Выберите время из списка</option>
                                                    <?php foreach ($arr_time as $value):?>
                                                        <?php $selected = @$_POST['in_time'] == $value ? 'selected' : ""; ?>
                                                        <option <?php echo $selected; ?> value="<?php echo $value; ?>">К <?php echo $value; ?></option>
                                                    <?php endforeach; ?>
                                                       <option>Нет указанного времени, уточнить у оператора</option>
                                                  </select>
                                                </div>
                                                <div class="col-12 col-12 mb--20"> 
                                                   <label for="person_count">
                                                        Количество персон
                                                   </label><br>
                                                    <input name="person_count" id="person_count" type="number" min="1" max="30" value="<?php echo @$_POST['person_count'];?>">
                                                    <?php if (isset($errors['person_count'])): ?>
                                                        <label id="person_count-error" class="error" for="person_count"><?php echo $errors['person_count']; ?></label>
                                                    <?php endif; ?>
                                                </div>
                                                <div class="col-12 col-12 mb--20"> 
                                                    <label for="training_chopsticks">
                                                        Количество учебных палочек
                                                    </label><br>
                                                    <input name="training_chopsticks" id="training_chopsticks" type="number" min="0" max="30" value="<?php echo @$_POST['training_chopsticks'];?>"> 
                                                    <?php if (isset($errors['training_chopsticks'])): ?>
                                                        <label id="training_chopsticks-error" class="error" for="training_chopsticks">
                                                            <?php echo $errors['training_chopsticks']; ?>
                                                        </label>
                                                    <?php endif; ?>
                                                </div> 
                                                <div class="col-12 col-12 mb--20"> 
                                                    <label for="comment">
                                                      Комментарий к заказу
                                                    </label><br>
                                                    <textarea name="comment" id="comment" cols="60" rows="3" ><?php echo @$_POST['comment'];?></textarea>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <!-- Payment Method -->
                                    <div class="single-accordion">
                                        <a class="accordion-head collapsed" data-toggle="collapse" data-parent="#checkout-accordion" href="#payment-method">3. Способ оплаты</a>
                                        <div id="payment-method" class="collapse show">
                                            <div class="accordion-body payment-method fix">
                                                
                                                    <?php foreach ($payment_type as $key => $value):?>
                                                     <div class="form-check">
                                                        <input class="form-check-input" type="radio" id="<?php echo $key;?>" name="payment_type" value="<?php echo @$_POST['payment_type'];?>">
                                                        <label class="form-check-label" for="<?php echo $key;?>"><?php echo $value; ?></label>
                                                   </div>
                                                    <?php endforeach; ?>
                                                    <div class="change_for">
                                                        <label for="change_for">Сдача с</label>
                                                        <input name="change_for" id="change_for" type="text" value="<?php echo @$_POST['change_for']; ?>" placeholder="1000 руб.">
                                                        <?php if (isset($errors['change_for'])):?>
                                                            <label id="change_for-error" class="error" for="change_for">
                                                                <?php echo $errors['change_for']; ?>
                                                            </label>
                                                        <?php endif; ?>
                                                    </div>
                                               
                                              <!--  <ul class="payment-method-list" name="payment_type">
                                                    <li class="active" value="<?php echo @$_POST['payment_type'];?>"><?php echo $payment_type[0];?></li>
                                                    <li><?php echo $payment_type[1]; ?></li>
                                                    <li class="payment-form-toggle" value="<?php echo @$_POST['payment_type'];?>"><?php echo $payment_type[2]; ?></li>
                                                </ul>-->
                                                <!--<div class="change_for">
                                                    <label for="change_for">Сдача с</label>
                                                    <input name="change_for" id="change_for" type="text" value="<?php echo @$_POST['change_for']; ?>" placeholder="1000 руб.">
                                                    <?php if (isset($errors['change_for'])):?>
                                                        <label id="change_for-error" class="error" for="change_for">
                                                            <?php echo $errors['change_for']; ?>
                                                        </label>
                                                    <?php endif; ?>
                                                </div>-->
                                            </div>
                                        </div>
                                    </div>
                                    
                                </div><!-- Checkout Accordion Start -->
                        </div>
                                
                                <!-- Order Details -->
                        <div class="col-lg-6 col-12 mb-30">
                           
                            <div class="order-details-wrapper">
                                <h2>Ваш заказ</h2>
                                <div class="order-details">
                                        <ul>
                                            <li>
                                                <p class="strong">Продукт</p>
                                                <p class="strong">Цена</p>
                                            </li>
                                            <?php foreach ($data['items'] as $product_cart):?>
                                            <li>
                                                <p>
                                                    <?php echo $product_cart['name']; ?> X <?php echo $product_cart['quantity'];?>шт.
                                                </p>
                                                <p><?php echo $product_cart['price']; ?>&nbsp;&#8381;</p>
                                            </li>
                                            <?php endforeach; ?>
                                            <li>
                                                <p class="strong">ПРОМЕЖУТОЧНЫЙ ИТОГ КОРЗИНЫ</p>
                                                <p class="strong"><?php echo $data['total_price']; ?>&nbsp;&#8381;</p>
                                            </li>
                                            <li><p class="strong">доставка</p>
                                                <?php if ($data['total_price'] < 500):?>
                                                <p><?php echo $delivery_cost; ?>&nbsp;&#8381;</p>
                                            </li>
                                            <li>  
                                                <p class="strong">ВСЕГО К ОПЛАТЕ</p>
                                                <p class="strong"><?php echo $data['total_price']+$delivery_cost; ?>&nbsp;&#8381;</p>
                                                <?php   else : ?>
                                                <label for="free">БЕСПЛАТНО</label>
                                            </li>
                                            <li><p class="strong">ВСЕГО К ОПЛАТЕ</p><p class="strong"><?php echo $data['total_price']; ?>&nbsp;&#8381;</p></li>
                                            <?php endif; ?>
                                            <li><button class="food__btn" name ="submit" type="submit">ОФОРМИТЬ ЗАКАЗ</button></li>
                                        </ul>
                                </div>
                            </div>
                        </form>       
                        </div>
                        
                    </div>
                </div>
            </div><!-- Checkout Section End-->             
         </section>   
        <!-- Start Footer Area -->
        <?php require_once("footer.phtml"); ?>
        <!-- End Footer Area -->
        <!-- Login Form -->
        <?php require_once("login_wrapper.phtml"); ?>
        <!-- //Login Form -->
            <!-- Cartbox -->
        <?php require_once("cartbox.phtml"); ?>
        <!-- //Cartbox -->  
    </div><!-- //Main wrapper -->

    <!-- JS Files -->
    <?php require_once("bottom.phtml"); ?>

</body>
</html>
