<?php  require_once("top.phtml"); ?>
</head>
<body>
    <!--[if lte IE 9]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
    <![endif]-->

    <!-- Add your site or application content here -->
    
    <!-- <div class="fakeloader"></div> -->

    <!-- Main wrapper -->
    <div class="wrapper" id="wrapper">
        <!-- Start Header Area -->
        <?php require_once("header.phtml"); ?>
        <!-- End Header Area -->
        <!-- Start Bradcaump area -->
        <div class="ht__bradcaump__area bg-image--18">
            <div class="ht__bradcaump__wrap d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <div class="bradcaump__inner text-center">
                                <h2 class="bradcaump-title">Оформить заказ</h2>
                                <nav class="bradcaump-inner">
                                  <a class="breadcrumb-item" href="/?section=index">Главня</a>
                                  <span class="brd-separetor"><i class="zmdi zmdi-long-arrow-right"></i></span>
                                  <span class="breadcrumb-item active">Оформить заказ</span>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Bradcaump area --> 
         <section class="htc__checkout bg--white section-padding--lg">
            <!-- Checkout Section Start-->
            <div class="checkout-section">
                <div class="container">
                    <div class="row">
                          
                        <div class="col-lg-6 col-12 mb-30">
                            <form action="" method="POST" class="billing-form checkout-form">    
                                    <!-- Checkout Accordion Start -->
                                <div id="checkout-accordion"> 
                                    <!-- Billing Method -->
                                    
                                    <div class="single-accordion">
                                        <a class="accordion-head collapsed" data-toggle="collapse" data-parent="#checkout-accordion" href="#billing-method">1. Платежная информация</a>
                                        <div id="billing-method" class="collapse show">

                                            <div class="accordion-body billing-method fix">
                                                <div class="row">
                                                    <div class="col-md-6 col-12 mb--20">                                 
                                                        <input type="text" name="client_name" value="<?php echo @$_POST['client_name'];?>" placeholder="Как Вас зовут *">
                                                        <?php if (isset($errors['client_name'])) : ?>
                                                            <label id="client_name-error" class="error" for="client_name"><?php echo $errors['client_name']; ?></label>
                                                        <?php endif; ?>
                                                    </div>
                                                    <div class="col-md-6 col-12">                                   
                                                        <input type="text" name="client_phone" value="<?php echo @$_POST['client_phone'];?>" placeholder="Номер телефона *">
                                                    </div> 
                                                    <div class="col-12 mb--20">
                                                        <select name="addr_city">
                                                          <option value="0" selected disabled>Ваш город *</option>
                                                          <option value="Севастополь">Севастополь</option>
                                                          <option value="Симферополь">Симферополь</option>
                                                        </select>
                                                    </div>
                                                    <div class="col-12 mb--20">
                                                        <input type="text" name="addr_street" value="<?php echo @$_POST['addr_street']; ?>" placeholder="Улица/Проспект *">
                                                    </div>
                                                    <div class="col-md-4 mb--20">
                                                        <input type="text" name="addr_build" value="<?php echo @$_POST['addr_build']; ?>" placeholder="Дом *" >
                                                    </div>
                                                    <div class="col-md-4 mb--20">
                                                        <input type="text" name="addr_flat" value="<?php echo @$_POST['addr_flat']; ?>" placeholder="Квартира">
                                                    </div>
                                                    <div class="col-md-4 col-12 mb--20">                                 
                                                        <input type="text" name="addr_domophone_code" value="<?php echo @$_POST['addr_domophone_code']; ?>" placeholder="Домофон">
                                                    </div>  
                                                    <div style="color: red">
                                                        Поля со звездочкой * ОБЯЗАТЕЛЬНЫ к заполнению
                                                    </div>                                
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <!-- Shipping Method -->
                                    <div class="single-accordion">
                                        <a class="accordion-head collapsed" data-toggle="collapse" data-parent="#checkout-accordion" href="#shipping-method">2. Информация о заказе</a>
                                        <div id="shipping-method" class="collapse">
                                            <div class="accordion-body shipping-method fix">
                                                <div class="col-12 col-12 mb--20">                                 
                                                  <label for="in_time">
                                                        К какому времени доставить заказ?
                                                  </label><br>
                                                  <select name="in_time" id="in_time">
                                                      
                                                  </select>
                                                </div>
                                                <div class="col-12 col-12 mb--20"> 
                                                   <label for="person_count">
                                                        Количество персон
                                                   </label><br>
                                                    <input name="person_count" id="person_count" type="number" min="1" max="30" value="1">
                                                </div>
                                                <div class="col-12 col-12 mb--20"> 
                                                    <label for="training_chopsticks">
                                                        Количество учебных палочек
                                                    </label><br>
                                                    <input name="training_chopsticks" id="training_chopsticks" type="number" min="0" max="30" value="0">  
                                                </div> 
                                                <div class="col-12 col-12 mb--20"> 
                                                    <label for="comment">
                                                      Комментарий к заказу
                                                    </label><br>
                                                    <textarea name="comment" id="comment" cols="60" rows="3"></textarea>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <!-- Payment Method -->
                                    <div class="single-accordion">
                                        <a class="accordion-head collapsed" data-toggle="collapse" data-parent="#checkout-accordion" href="#payment-method">3. Способ оплаты</a>
                                        <div id="payment-method" class="collapse">
                                            <div class="accordion-body payment-method fix">
                                               
                                                <ul class="payment-method-list">
                                                    <li class="active">Он-лайн</li>
                                                    <li>Картой при получении</li>
                                                    <li class="payment-form-toggle">Оплата наличными</li>
                                                </ul>
                                                <div class="change_for">
                                                    <label for="change_for">Сдача с</label>
                                                    <input name="change_for" id="change_for" type="text" placeholder="1000 руб.">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    
                                </div><!-- Checkout Accordion Start -->
                        </div>
                                
                                <!-- Order Details -->
                        <div class="col-lg-6 col-12 mb-30">
                           
                            <div class="order-details-wrapper">
                                <h2>Ваш заказ</h2>
                                <div class="order-details">
                                        <ul>
                                            <li><p class="strong">Продукт</p><p class="strong">Цена</p></li>
                                            <li><p>Fishing Reel x1</p><p>$104.99</p></li>
                                            <li><p>Fishing Rods x1 </p><p>$85.99</p></li>
                                            <li><p class="strong">ПРОМЕЖУТОЧНЫЙ ИТОГ КОРЗИНЫ</p><p class="strong">$190.98</p></li>
                                            <li><p class="strong">доставка</p><p>
                                                <input type="radio" name="order-shipping" id="flat" /><label for="flat">Flat Rate $ 7.00</label><br />
                                                <input type="radio" name="order-shipping" id="free" /><label for="free">        БЕСПЛАТНО</label>
                                            </p></li>
                                            <li><p class="strong">ВСЕГО К ОПЛАТЕ</p><p class="strong">$190.98</p></li>
                                            <li><button class="food__btn" name ="submit" type="submit">ОФОРМИТЬ ЗАКАЗ</button></li>
                                        </ul>
                                </div>
                            </div>
                        </form>       
                        </div>
                        
                    </div>
                </div>
            </div><!-- Checkout Section End-->             
         </section>   
        <!-- Start Footer Area -->
        <?php require_once("footer.phtml"); ?>
        <!-- End Footer Area -->
        <!-- Login Form -->
        <?php require_once("login_wrapper.phtml"); ?>
        <!-- //Login Form -->
            <!-- Cartbox -->
        <?php require_once("cartbox.phtml"); ?>
        <!-- //Cartbox -->  
    </div><!-- //Main wrapper -->

    <!-- JS Files -->
    <?php require_once("bottom.phtml"); ?>
</body>
</html>
