  <!-- Login Form -->
        <div class="accountbox-wrapper">
            <div class="accountbox text-left">
                <ul class="nav accountbox__filters" id="myTab" role="tablist">
                    <li>
                        <a class="active" id="log-tab" data-toggle="tab" href="#log" role="tab" aria-controls="log" aria-selected="true">Вход</a>
                    </li>
                    <li>
                        <a id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Регистрация</a>
                    </li>
                </ul>
                <div class="accountbox__inner tab-content" id="myTabContent">
                    <div class="accountbox__login tab-pane fade show active" id="log" role="tabpanel" aria-labelledby="log-tab">
                        <form action="#">
                            <div class="single-input">
                                <input class="cr-round--lg" type="text" id="auth_phone" placeholder="Номер телефона">
                                <div id="error-phone" name="errors"></div>
                            </div>
                            <div class="single-input">
                                <input class="cr-round--lg" type="password" id="auth_password" placeholder="Пароль">
                                <div id="error-password" name="errors"></div>
                            </div>
                            <div class="single-input">
                                <button type="submit" id="auth_submit" class="food__btn"><span>Вперёд</span></button>
                            </div>
                            <div class="accountbox-login__others">
                                <h6>Войти с помощью</h6>
                                <div class="social-icons">
                                    <ul>
                                        <li class="facebook"><a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a></li>
                                        <li class="twitter"><a href="https://twitter.com/"><i class="fa fa-twitter"></i></a></li>
                                        <li class="pinterest"><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                    </ul>
                                </div>                            
                            </div>
                        </form>
                    </div>
                    <div class="accountbox__register tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                        <div id="s1">
                            <div class="single-input">
                                <input class="cr-round--lg" type="text" id="firstname"  placeholder="Имя">
                                <div id="error-firstname" name="errors"></div>
                            </div>
                            <div class="single-input">
                                <input class="cr-round--lg" type="text" id="secondname" placeholder="Фамилия">
                                <div  id="error-secondname" name="errors"></div>
                            </div>
                            <div class="single-input">
                                <input class="cr-round--lg" type="text" id="phone" placeholder="Номер телефона">
                                <div id="error-phone" name="errors"></div>
                                <div id="warning-phone" name="warning"></div>
                            </div>
                            <div class="single-input">
                                <input class="cr-round--lg" type="password" id="password" placeholder="Пароль">
                                <div id="error-password" name="errors"></div>
                            </div>
                            <div class="single-input">
                                <input class="cr-round--lg" type="password" id="re_password" placeholder="Повтор пароля">
                                <div id="error-re_password" name="errors"></div>
                            </div>
                            <div class="single-input">
                                <button id="reg_submit" class="food__btn"><span>Зарегистрироваться</span></button>
                            </div>
                        </div>
                        <div id="s2" style="display: none;">
                          <div class="single-input">
                                <input class="cr-round--lg" type="text" id="code" placeholder="Введите последние 6-ть цифр номера со входящего звонка">
                                <div id="error-code" name="errors"></div>
                            </div>
                            <div class="single-input">
                                <button id="reg_finish" class="food__btn"><span>Завершить регистрацию</span></button>
                            </div>  
                        </div>
                        <div id="s3" style="display: none;">
                          РЕГИСТРАЦИЯ ПРОШЛА УСПЕШНО!!! 
                        </div>
                    </div>
                    <span class="accountbox-close-button"><i class="zmdi zmdi-close"></i></span>
                </div>
            </div>
        </div><!-- //Login Form -->

