<!doctype html>
<html class="no-js" lang="zxx">
<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<title>Aahar || Food Delivery Html5 Template</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Favicons -->
	<link rel="shortcut icon" href="images/favicon.ico?date=<?php echo date('Y-m-d|H:i:s', filemtime('images/favicon.ico'));?>">
	<link rel="apple-touch-icon" href="images/icon.png?date=<?php echo date('Y-m-d|H:i:s', filemtime('images/icon.png'));?>">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="css/bootstrap.min.css">
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
	<link rel="stylesheet" href="css/plugins.css">
	<link rel="stylesheet" href="style.css?date=<?php echo date('Y-m-d|H:i:s', filemtime('style.css'));?>">

	<!-- Cusom css -->
 <link rel="stylesheet" href="css/custom.css?date=<?php echo date('Y-m-d|H:i:s', filemtime('css/custom.css'));?>">

 <!-- Modernizer js -->
 <script src="js/vendor/modernizr-3.5.0.min.js"></script>